# Generated by Django 4.2.20 on 2025-04-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', 'XXXX_create_initial_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_settings', 'Can access settings page'), ('manage_users', 'Can manage users'), ('view_reports', 'Can view reports')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
