# Generated by Django 4.2.20 on 2025-04-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0002_sale_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
