# Generated by Django 4.2.20 on 2025-04-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0003_alter_product_primary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_image',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='proof_image',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
