# Generated by Django 4.2.20 on 2025-04-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0006_create_default_admin'),
        ('inventory_api', '0006_user_force_password_change_businesssettings'),
        ('inventory_api', '0007_create_default_admin'),
    ]

    operations = [
    ]
