# Generated by Django 4.2.20 on 2025-04-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0008_create_default_business_settings'),
        ('inventory_api', '0008_merge_20250422_1044'),
    ]

    operations = [
    ]
