# Generated by Django 4.2.20 on 2025-04-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0001_alter_user_options_alter_user_force_password_change_and_more'),
        ('inventory_api', '0009_merge_20250422_1046'),
    ]

    operations = [
    ]
