# Generated by Django 4.2.20 on 2026-01-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0014_payment_terminal_alter_payment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'MPESA'), ('equity', 'Equity'), ('credit', 'Credit'), ('card', 'Card'), ('mobile', 'Mobile Payment')], max_length=10),
        ),
    ]
